# Site settings
title: Jason & Shelley's Wedding
email:
description: "Website for our big day"
baseurl: # the subpath of your site, e.g. /blog/
url: "http://jason-shelley-wedding.com/" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line: MV Skansonia
  - line: 205 NE Northlake Way 
  - line: Seattle, WA 98105
  # Feel free to add more lines here
telephone:
copyright:

# API settings
google_api_key: AIzaSyA67YHPnJ1xmumEBhG5bmceWYvGuU4F6W4

# Build settings
markdown: kramdown
